# Generated by Django 6.0.5 on 2026-09-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiuser',
            name='device_mac',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
