# Generated by Django 6.0.5 on 2026-09-24 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_client_bank_account_name_client_bank_account_number_and_more'),
        ('client', '0003_receipt_payment_status'),
        ('routers', '0003_router_connection_token_router_last_seen_and_more'),
        ('wifi', '0003_wifiuserdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('session_id', models.CharField(max_length=128, unique=True)),
                ('framed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, default='', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('input_mb', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('output_mb', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_online', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radius_sessions', to='accounts.client')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routers.router')),
            ],
        ),
        migrations.CreateModel(
            name='PppoeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_mac', models.CharField(blank=True, default='', max_length=20)),
                ('online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('data_in_mb', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('data_out_mb', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_users', to='accounts.client')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.package')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pppoe_users', to='routers.router')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('client', 'username'), name='unique_client_pppoe_username')],
            },
        ),
    ]
