# Generated by Django 6.0.5 on 2026-07-18 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_business_name_client_name_remove_client_logo_and_more'),
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='accounts.client'),
        ),
    ]
