# Generated by Django 6.0.5 on 2026-09-24 14:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0002_alter_router_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='connection_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: [
                setattr(router, 'connection_token', uuid.uuid4().hex) or router.save(update_fields=['connection_token'])
                for router in apps.get_model('routers', 'Router').objects.filter(connection_token__isnull=True)
            ],
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='router',
            name='connection_token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='router',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='api_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='router',
            name='api_username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='router',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='router',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
