# Generated by Django 6.0.5 on 2026-09-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0003_router_connection_token_router_last_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='has_public_ip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='router',
            name='router_os_version',
            field=models.CharField(choices=[('universal', 'Universal'), ('routeros7', 'RouterOS 7'), ('routeros6', 'RouterOS 6')], default='universal', max_length=20),
        ),
        migrations.AlterField(
            model_name='router',
            name='api_password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='router',
            name='api_username',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
