# Generated by Django 6.0.5 on 2026-09-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_business_name_client_name_remove_client_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='billing_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='wifi_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
