# Generated by Django 6.0.7 on 2026-09-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_client_billing_info_client_logo_client_wifi_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mpesa_callback_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='mpesa_consumer_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='mpesa_consumer_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='mpesa_environment',
            field=models.CharField(default='sandbox', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='mpesa_passkey',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='mpesa_shortcode',
            field=models.CharField(blank=True, default='174379', max_length=20),
        ),
    ]
