# Generated by Django 6.0.5 on 2026-09-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_client_mpesa_callback_url_client_mpesa_consumer_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_branch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_swift_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='billing_account_type',
            field=models.CharField(default='till', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='mpesa_confirmation_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='mpesa_validation_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='paybill_account_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='paybill_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='till_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
